package com.github2.generator.javatojava;

import com.github2.enums.MappingType;
import com.github2.model.ElementNode;
import com.github2.parser.java.JavaParser;
import com.github2.generator.javatojava.buildertype.BuilderTypeCodeGenerator;
import com.github2.generator.javatojava.normaltype.NormalTypeCodeGenerator;
import com.intellij.psi.JavaPsiFacade;
import com.intellij.psi.search.GlobalSearchScope;
import lombok.Builder;

import java.util.List;

@Builder
public class JavaToJavaCodeGenerator {
    private final String objectToSetQualifiedName;
    private final String objectToGetVariableName;
    private final String objectToGetQualifiedName;
    private final MappingType mappingType;
    private final List<ElementNode> elementsToSet;
    private final List<ElementNode> elementsToGet;

    public String generateMappingCode() {

        if (elementsToGet.size() == 0 || elementsToSet.size() == 0)
            return "";

        StringBuilder result = new StringBuilder();

        if (mappingType == MappingType.BUILDER) {
            BuilderTypeCodeGenerator builderTypeCodeGenerator = BuilderTypeCodeGenerator.builder()
                    .elementsToGet(elementsToGet)
                    .elementsToSet(elementsToSet)
                    .objectToGetVariableName(objectToGetVariableName)
                    .objectToSetQualifiedName(objectToSetQualifiedName)
                    .build();
            String mappingCode = builderTypeCodeGenerator.generateMappingCode();
            result.append(mappingCode);
        } else {
            NormalTypeCodeGenerator normalTypeCodeGenerator = NormalTypeCodeGenerator.builder()
                    .elementsToGet(elementsToGet)
                    .elementsToSet(elementsToSet)
                    .objectToGetVariableName(objectToGetVariableName)
                    .objectToSetQualifiedName(objectToSetQualifiedName)
                    .build();
            String mappingCode = normalTypeCodeGenerator.generateMappingCode();
            result.append(mappingCode);
        }

        result.append("\n // Generated by mapping-generator !!! \n");

        return result.toString();
    }


}
