package com.github.codegenerator.javatojava;

import com.github.codegenerator.javatojava.buildertype.BuilderTypeCodeGenerator;
import com.github.codegenerator.javatojava.normaltype.NormalTypeCodeGenerator;
import com.github.enums.MappingType;
import com.github.model.ElementNode;
import com.github.parser.java.JavaParser;
import com.github.utils.JavaCommandUtils;
import com.intellij.psi.JavaPsiFacade;
import com.intellij.psi.PsiJavaFile;
import com.intellij.psi.codeStyle.JavaCodeStyleManager;
import com.intellij.psi.search.GlobalSearchScope;
import lombok.Builder;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Builder
public class JavaToJavaCodeGenerator {
    private final String objectToSetQualifiedName;
    private final String objectToGetVariableName;
    private final String objectToGetQualifiedName;
    private final MappingType mappingType;
    private final JavaPsiFacade javaPsiFacade;
    private final GlobalSearchScope globalSearchScope;
    private final Set<String> referredQualifiedName;

    public String generateMappingCode() {

        JavaParser setParser = JavaParser.builder()
                .javaPsiFacade(javaPsiFacade)
                .globalSearchScope(globalSearchScope)
                .build();
        List<ElementNode> elementsToSet = setParser.parse(objectToSetQualifiedName);
        JavaParser getParser = JavaParser.builder()
                .javaPsiFacade(javaPsiFacade)
                .globalSearchScope(globalSearchScope)
                .build();
        List<ElementNode> elementsToGet = getParser.parse(objectToGetQualifiedName);

        if (elementsToGet.size() == 0 || elementsToSet.size() == 0)
            return "";

        StringBuilder result = new StringBuilder();
        if (mappingType == MappingType.BUILDER) {
            result.append(forBuilder(elementsToSet, elementsToGet, referredQualifiedName));
        } else {
            result.append(forNormal(elementsToSet, elementsToGet, referredQualifiedName));
        }

        result.append("\n // Generated by mapping-generator !!! \n");

        return result.toString();
    }

    private String forBuilder(List<ElementNode> elementsToSet, List<ElementNode> elementsToGet, Set<String> referredQualifiedName) {
        BuilderTypeCodeGenerator builderTypeCodeGenerator = BuilderTypeCodeGenerator.builder()
                .elementsToSet(elementsToSet)
                .elementsToGet(elementsToGet)
                .objectToGetVariableName(objectToGetVariableName)
                .objectToSetQualifiedName(objectToSetQualifiedName)
                .referredQualifiedName(referredQualifiedName)
                .build();
        return builderTypeCodeGenerator.generateMappingCode();
    }

    private String forNormal(List<ElementNode> elementsToSet, List<ElementNode> elementsToGet, Set<String> referredQualifiedName) {
        NormalTypeCodeGenerator normalTypeCodeGenerator = NormalTypeCodeGenerator.builder()
                .elementsToGet(elementsToGet)
                .elementsToSet(elementsToSet)
                .objectToGetVariableName(objectToGetVariableName)
                .objectToSetQualifiedName(objectToSetQualifiedName)
//                .referredQualifiedName(referredQualifiedName)
                .build();
        return normalTypeCodeGenerator.generateMappingCode();
    }
}
